#!/usr/bin/env python3
"""Writes data/v1/manifest.json: the content hash of every published runtime file.

Clients fetch this one file per startup, conditionally (If-None-Match), and re-download only
the entries whose hash moved. The repository's commit id would not do: it also moves for
fixtures/, vectors/ and prose commits, which no client fetches, and it cannot say WHICH of the
twelve runtime files changed.

Run after any change under data/v1/, including a hand-published overlay table. validate.py
fails when the manifest disagrees with the files, so a forgotten run is caught before publish.
"""
import datetime
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data/v1"
MANIFEST = DATA_DIR / "manifest.json"
# The manifest cannot hash itself, and LICENCE is not a file any client fetches.
EXCLUDED = {"manifest.json", "LICENSE"}


def hashes():
    """Every published runtime file's sha256, keyed by the name clients request it under."""
    return {
        path.name: hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(DATA_DIR.iterdir())
        if path.is_file() and path.name not in EXCLUDED
    }


def render(files, generated):
    return json.dumps({
        "_comment": "Content hashes of the published runtime files. Generated by "
                    "tools/manifest.py; do not hand-edit.",
        "generated": generated,
        "files": files,
    }, indent=1) + "\n"


def main():
    files = hashes()
    MANIFEST.write_text(render(files, datetime.date.today().isoformat()), encoding="utf-8")
    print(f"manifest: {len(files)} files")


if __name__ == "__main__":
    main()
